


# a=int(input("Enter the number:"))
# i=5
# while i<=a:
#     j=a
    # while j>=i-1:       #  ***
#         print(j,end=" ") # **
#         j-=1             # *
#     print()
#     i+=1    










#     rows = int(input("Enter the number of rows: "))  
# for i in range(0, rows + 1):  
#     # inner loop for decrement in i values  
#     for j in range(rows - i, 0, -1):  
#         print(j, end=' ')  
#     print()  
